
development:
  adapter: mysql2
  encoding: utf8
  database: deskhack_dev
  pool: 5
  username: deskhack_dev
  password: deskhack_dev

test:
  adapter: mysql2
  encoding: utf8
  database: deskhack_test
  username: deskhack_test
  password: deskhack_test

production:
  adapter: mysql2
  encoding: utf8
  database: deskhack_production
  pool: 5
  username: deskhack
  password: <%= ENV['DESKHACK_DATABASE_PASSWORD'] %>
